# WhatATheme
# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
# URL of the Site
url: https://taeyeong132.github.io
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Code highlighter
highlighter: rouge

# Title of the Site
title: TAE YEONG YU
# Description of the Site
description: AI Developer
# URL of Image of the Site
site-image: https://avatars.githubusercontent.com/u/88639688?v=4
# Keywords of the Site
site-keywords: AI, Diffusion, Generative Models, Embedded
# URL for the Image of custom Favicon
favicon-url: 

darkmode_switch: true

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://github.com/taeyeong132/taeyeong132.github.io/blob/master/custom/%EB%B0%B0%EB%84%88%EC%82%AC%EC%A7%84.png?raw=true
heroimage_dark: https://github.com/taeyeong132/taeyeong132.github.io/blob/master/custom/%EB%B0%B0%EB%84%88%EC%82%AC%EC%A7%84.png?raw=true

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: taeyoun9@gmail.com
facebook_username:
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  taeyeong132
youtube_channel_id: 
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: G-KFNS88G1GM

# Disqus
disqus-shortname:

# Name of the Author
author-name: TaeYeong
# URL for the Image of the Author
author-image: https://github.com/taeyeong132/taeyeong132.github.io/blob/master/custom/%EC%A6%9D%EB%AA%85%EC%82%AC%EC%A7%84.jpg?raw=true
# 60 Words About the Author
author-about: Konkuk University, Electrical Electronic Engineering, Diffusion, Artificial intelligence, Deep learning, Embedded
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/taeyeong132

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/